/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.emp.gl.gui;

import java.awt.event.KeyEvent;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.emp.gl.core.lookup.Lookup;
import org.emp.gl.messages.AnonymousMessage;
import org.emp.gl.messages.BaseMessageAdapter;
import org.emp.gl.messages.HashSimple;
import org.emp.gl.messages.UpperCase;
import org.emp.gl.messages.IMessage;
import org.emp.gl.messages.Md5;
import org.emp.gl.messages.RemovePonctuation;
import org.emp.gl.messages.RemoveSpaces;
import org.emp.gl.messages.SHA;
import org.emp.gl.messages.AES;
import org.emp.gl.messages.Shift;
import org.emp.gl.sender.service.MessagingService;

/**
 *
 * @author billal
 */
public class MessagingSenderGui extends javax.swing.JFrame {

    private final String senderId;
    public IMessage message;

    /**
     * Creates new form MessagingRecievingTest
     *
     * @param senderId
     */
    public MessagingSenderGui(String senderId) {
        setSize(400, 400);
        this.senderId = senderId;

        initComponents();

        userField.setText(senderId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        destinationField = new javax.swing.JTextField();
        objectField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageField = new javax.swing.JTextArea();
        upperCase = new javax.swing.JCheckBox();
        removePonctuation = new javax.swing.JCheckBox();
        removeSpaces = new javax.swing.JCheckBox();
        anonymous = new javax.swing.JCheckBox();
        shiftValue = new javax.swing.JTextField();
        integrity = new javax.swing.JComboBox<>();
        encryption = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jCheckBox6.setText("jCheckBox6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Emetteur :");

        userField.setEditable(false);
        userField.setText("ID-241");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Destinataire :");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Objet :");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Message :");

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        destinationField.setText("ID-1");

        messageField.setColumns(40);
        messageField.setRows(5);
        jScrollPane1.setViewportView(messageField);

        upperCase.setText("Majuscule");
        upperCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upperCaseActionPerformed(evt);
            }
        });

        removePonctuation.setText("Sans Ponctuation");
        removePonctuation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePonctuationActionPerformed(evt);
            }
        });

        removeSpaces.setText("Sans Espaces");
        removeSpaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSpacesActionPerformed(evt);
            }
        });

        anonymous.setText("Anonyme");
        anonymous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anonymousActionPerformed(evt);
            }
        });

        shiftValue.setVisible(false);
        shiftValue.setText("0");
        shiftValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shiftValueActionPerformed(evt);
            }
        });

        integrity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"None" ,"Hash Simple","SHA", "MD5"}));
        integrity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                integrityActionPerformed(evt);
            }
        });

        encryption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Decalage", "AES" }));
        encryption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptionActionPerformed(evt);
            }
        });

        jLabel6.setText("Filltrage");

        jLabel7.setText("Intégrité");

        jLabel8.setText("Cryptage");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(34, 34, 34)
                                .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(anonymous))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(20, 20, 20)
                                .addComponent(destinationField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(51, 51, 51)
                                .addComponent(objectField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(upperCase)
                            .addComponent(removePonctuation)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel6))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(removeSpaces))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(integrity, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(encryption, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(shiftValue, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anonymous))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(destinationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(objectField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(upperCase)
                        .addGap(7, 7, 7)
                        .addComponent(removePonctuation)
                        .addGap(7, 7, 7)
                        .addComponent(removeSpaces)
                        .addGap(0, 34, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(integrity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(encryption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shiftValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        this.message = new BaseMessageAdapter();

        message.setTitle(objectField.getText());
        message.setMessage(messageField.getText());
        message.setSender(userField.getText());

        // Décors sur le format
        if (removePonctuation.isSelected()) {
            removePonctuationActionPerformed(evt);
        }
        if (removeSpaces.isSelected()) {
            removeSpacesActionPerformed(evt);
        }
        if (upperCase.isSelected()) {
            upperCaseActionPerformed(evt);
        }

        if (anonymous.isSelected()) {
            anonymousActionPerformed(evt);
        }
        if(integrity.isEnabled()){
            integrityActionPerformed(evt);
        }
        if(encryption.isEnabled()){
            encryptionActionPerformed(evt);
        }
            

        MessagingService ms = Lookup.getInstance().getService(MessagingService.class);
        ms.sendMessage(destinationField.getText(), message.toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void upperCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upperCaseActionPerformed
        if (message != null) {
            message = new UpperCase(this.message);
        }
    }//GEN-LAST:event_upperCaseActionPerformed

    private void removePonctuationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePonctuationActionPerformed
        if (message != null) {
            message = new RemovePonctuation(this.message);
        }
    }//GEN-LAST:event_removePonctuationActionPerformed

    private void removeSpacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSpacesActionPerformed
        if (message != null) {
            message = new RemoveSpaces(this.message);
        }
    }//GEN-LAST:event_removeSpacesActionPerformed

    private void anonymousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anonymousActionPerformed
        if (message != null) {
            message = new AnonymousMessage(this.message);
        }
    }//GEN-LAST:event_anonymousActionPerformed

    private void shiftValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftValueActionPerformed
        // TODO add your handling code here:String
        
    }//GEN-LAST:event_shiftValueActionPerformed

    private void integrityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_integrityActionPerformed
        // TODO add your handling code here
        if (integrity.getSelectedItem().equals("None")) {
            
        
        }
        if (integrity.getSelectedItem().equals("Hash Simple")) {
            if (message != null) {
            message = new HashSimple(this.message);
        }
        }
        if (integrity.getSelectedItem().equals("SHA")) {
            if (message != null) {
            try {
                message = new SHA(this.message);
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(MessagingSenderGui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        }
        if (integrity.getSelectedItem().equals("MD5")) {
            if (message != null) {
            try {
                message = new Md5(this.message);
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(MessagingSenderGui.class.getName()).log(Level.SEVERE, null, ex);
             }
            }
        }

    }//GEN-LAST:event_integrityActionPerformed

    private void encryptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptionActionPerformed
        // TODO add your handling code here:
        if (encryption.getSelectedItem().equals("None")) {
 
        }
        if (encryption.getSelectedItem().equals("Decalage")) {
            shiftValue.setVisible(encryption.getSelectedItem().equals("Decalage"));
            if (message != null) {
                int shiftVal = 0;
                if (!shiftValue.getText().equals("")) {
                    shiftVal = new Integer(shiftValue.getText());
                }
                message = new Shift(this.message, shiftVal);
            }
        }
        
        if (encryption.getSelectedItem().equals("AES")) {
            if (message != null) {
            message = new AES(this.message);
            }
        }
        

    }//GEN-LAST:event_encryptionActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox anonymous;
    private javax.swing.JTextField destinationField;
    private javax.swing.JComboBox<String> encryption;
    private javax.swing.JComboBox<String> integrity;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea messageField;
    private javax.swing.JTextField objectField;
    private javax.swing.JCheckBox removePonctuation;
    private javax.swing.JCheckBox removeSpaces;
    private javax.swing.JTextField shiftValue;
    private javax.swing.JCheckBox upperCase;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
}
